# Generated by Django 5.0.2 on 2024-03-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWebApp', '0014_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='user',
            new_name='user_id',
        ),
    ]
