# Generated by Django 5.0.2 on 2024-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWebApp', '0015_rename_product_cartproduct_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttags',
            name='product',
            field=models.ManyToManyField(related_name='product_tag_set', to='ecomWebApp.product'),
        ),
    ]
